#   Copyright 2013 Ryan Rix <ry@n.rix.si>
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
- name: Nagios Instance
  hosts: nagios.myservers.com
  user: ec2-user
  sudo: True

  tasks:
  - name: Install nagios $item
    action: yum state=latest pkg=$item
    with_items:
    - nagios
    - nagios-plugins-all
    - nagios-devel

  - name: Copy in base config
    action: copy src=templates/nagios.cfg dest=/etc/nagios/nagios.cfg

  - name: copy in object config $item
    action: copy src=templates/$item dest=/etc/nagios/objects/$item
    with_items:
    - hostgroups.cfg
    - commands.cfg
    - contacts.cfg
    - timeperiods.cfg
    - templates.cfg

  - name: restart $item
    action: service name=$item state=restarted enabled=yes
    with_items:
    - nagios
    - httpd

- name: Set up base NRPE tasks for all hosts
  hosts: all
  user: root

  tasks:
    - include: nagios-nrpe.yml
